apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  volumes:
   - name: demo-vol
     configMap:
      name: postgres-config
      items:
        - key: postgresql.conf
          path: postgresql.conf
       
  containers:
    - name: postgres
      image: postgres
      volumeMounts:
        - mountPath: /mnt/data
          name: demo-vol
      env:
       - name: POSTGRES_PASSWORD
         valueFrom:
           secretKeyRef:
              key: postgres-password
              name: postgres-secret