apiVersion: v1
kind: PersistentVolume
metadata: 
   name: demo-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: "/mnt/data"