apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: odoo-data-claim # Sets name of PV
  namespace: odoo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: 5Gi # Sets volume size
